### ISSUE TITLE
'crest_sampling' energies

### ISSUE THREAD

**Issue by S1chemf** [lanl/Architector#23]
Hello,

I ran Architector with both crest_sampling=True and crest_sampling=False. It seems that, with the same system and parameters as with crest_sampling=True, the lowest energy conformer is found when crest_sampling=False. However, when I run a pure XTB calculation with these conformers, the conformer generated with crest_sampling=True is the lower energy conformer (as expected). Also, it seems that crest sampling is only working for the first conformer that is generated. The energies of the other conformers that are generated using crest_sampling=True and crest_sampling=False are the same.

Here is part of the code I used for generating the energies of the conformers with Architector:
'parameters': {
                "metal_ox": None, "metal_spin": None,
                "full_spin": metal_char[metal], "full_charge": charge,
                "full_method": "GFN2-xTB", "assemble_method": "GFN2-xTB",
                'xtb_solvent' : 'water', "xtb_accuracy": 1.0,
                "xtb_electronic_temperature": 300, "xtb_max_iterations": 250,
                'n_conformers':1, 'return_only_1': False, "n_symmetries": 10,
                "relax": True, "return_timings": True, "crest_sampling": True,
                "skip_duplicate_tests": False, "seed": 4009,
                "temp_prefix":"/tmp/", 'fill_ligand' : 0,
                "lig_assignment":'bruteforce'
            }}

    out = build_complex(inputDict)
    labels = list(out.keys())
    energies = [out[key]['energy'] for key in labels]
    print(energies)

Energies from Architector using crest_sampling=True:
conformer 1: -4378.617578128723, 
conformer 2: -4379.159332986936, 
conformer 3: -4378.833953072552, 
conformer 4: -4378.806020344315, 
conformer 5: -4378.45904487649, 
conformer 6: -4377.9454123290125

Energies from Architector using crest_sampling=False:
conformer 1: -4379.338968777023, 
conformer 2: -4379.159332986956, 
conformer 3: -4378.833953072535, 
conformer 4:-4378.806020344196,
conformer 5: -4378.459044876702, 
conformer 6: -4377.945412330159

Energy of conformer 1 using crest_sampling=True with pure XTB: -160.971411607424 Eh

Energy of conformer 1 using crest_sampling=False with pure XTB: -160.844187510375 Eh

**Comment by mgt16-LANL** [comment]
Hi @S1chemf, 

Thanks for raising this issue! I had attempted to document these crest options for more use - but think I'll add a whole notebook as documentation in a bit - in more broken-down form:
```python
# Note - use architector-0.0.10 or newer!
from architector import (build_complex,
                         convert_io_molecule,
                         view_structures)
```
```python
# First, let's build a reference set from Architector itself:
out1 = build_complex({'core':{'metal':'Fe',
                    'coreCN':6},
                     'ligands':['water']*6,
                     'parameters':{}})
```
Which gives:
<img width="1030" alt="image" src="https://github.com/lanl/Architector/assets/119455260/158eaf98-1acb-4de2-92af-397683868304">
Next,
```python
# Now request crest_sampling with only defaults:
out2 = build_complex({'core':{'metal':'Fe',
                    'coreCN':6},
                     'ligands':['water']*6,
                     'parameters':{
                         "crest_sampling": True,
                     }})
```
Gives:
<img width="1030" alt="image" src="https://github.com/lanl/Architector/assets/119455260/863bfb62-6427-4a52-b50a-cc85426077f2">
Next,
```python
# If we look at the defaults in architector the crest_options are:
# --gfn2//gfnff --noreftopo --nocross --quick"
# This by default does the CREST sampling with GFN-FF, then does SINGLE POINTS
# at the GFN2-xTB level of theory.

# Let's run again with different crest options (using --gfn2 for all steps!)
# This will automatically perform optimization as well.
# This will take much longer
out3 = build_complex({'core':{'metal':'Fe',
                    'coreCN':6},
                     'ligands':['water']*6,
                     'parameters':{
                         "crest_sampling": True,
                         # Switch to GFN2/GFN2
                         "crest_options":"--gfn2 --noreftopo --nocross --quick"
                     }})
```
Gives:
<img width="1030" alt="image" src="https://github.com/lanl/Architector/assets/119455260/4c1657ba-7498-4ba5-827b-50c75dbf67a6">

And finally, to perform sampling on all the conformers:
```python
# I wanted crest sampling on them all!
# - Note - this runs for several minutes on my laptop
out4 = build_complex({'core':{'metal':'Fe',
                    'coreCN':6},
                     'ligands':['water']*6,
                     'parameters':{
                         "crest_sampling": True,
                         # Switch to GFN2/GFN2
                         "crest_options":"--gfn2 --noreftopo --nocross --quick",
                         # You can specify Crest sampling on up to N conformers:
                         "crest_sampling_n_conformers": 3
                     }})
```
Gives:
<img width="1030" alt="image" src="https://github.com/lanl/Architector/assets/119455260/ffeab82b-8964-445f-9756-85ab7ed5e1ba">

I hope this helps explain how to play around with all these parameters!

Just make sure to have the updated version of architector installed!

**Comment by mgt16-LANL** [comment]
I added the full notebook over here: https://github.com/lanl/Architector/blob/Secondary_Solvation_Shell/documentation/Crest_Sampling_Documentation.ipynb

**Comment by mgt16-LANL** [comment]
I'm going to close - feel free to re-open if my comments and documentation didn't answer your question! Thanks again for the issue!
