### ISSUE TITLE
Architector conformer limit

### ISSUE THREAD

**Issue by psingams** [lanl/Architector#24]
I'm trying to generate ~40 conformers for a metal bound to a macrocycle ligand. I've tried changing the n_conformers variable to 40 but I only get 2 conformers every time I run the program.

[Conformer search.pdf](https://github.com/lanl/Architector/files/12500170/Conformer.search.pdf)

**Comment by mgt16-LANL** [comment]
Hi @psingams , Thanks for the question! Some of your questions might be answered by these prior two issues:

1 - https://github.com/lanl/Architector/issues/18 

I tried to illustrate and explain n_conformers and n_symmetries.

2 - https://github.com/lanl/Architector/issues/23 

I tried to show you can perform CREST local sampling around Architector minima if you are interested!

Beyond this - you can request to not perform duplicate checks (Architector removes structures that are nearly identical by default).

e.g. You can set:
"skip_duplicate_tests":True.


I'm sorry - just saw this this morning - hope you were able to find these types of answers!
